### PR TITLE
Fixes issue with datepicker not working correctly with Laravel 9.x

### PR DESCRIPTION
**Pull request by gkimpson**
Alpinejs 2.x source was added to the code breaking the datepicker

### CODE REVIEW

**Comment by gkimpson** [comment]
This fix should prevent the issue with duplicating the days row and errors regarding the day & date variables that I was getting in my Laravel 9.x app

**Comment by gkimpson** [comment]
actually.... i don't think my change did fix this - will re-open

**Comment by gkimpson** [comment]
@mkocansey This should hopefully fix the issue with the datepicker I mentioned in the issues section earlier today

**Comment by mkocansey** [comment]
@gkimpson I see you closed the PR?

**Comment by gkimpson** [comment]
I'll reopen it and you can assess if the fix I did works for you

**Comment by mkocansey** [comment]
Please reopen... the fix worked for me.

**Comment by mkocansey** [comment]
I made several other changes in `datepicker.blade.php` that will cause conflicts.. I'll just implement the change this side and add AlpineJs to the docs as a requirement. Thanks a lot for the tip.

**Comment by gkimpson** [comment]
No worries I'm glad the change worked - amazing library by the way I've been looking for something like this for ages and randomly saw it advertised on the laraveldaily YouTube channel. 👍🏾

**Pull request closed without merging**
